"""create pois table

Revision ID: 6523230a0e23
Revises: 2f2fe2a5ef11
Create Date: 2024-04-24 08:50:24.528509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6523230a0e23'
down_revision: Union[str, None] = '2f2fe2a5ef11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('ranking_out_of', sa.Integer(), nullable=True),
    sa.Column('num_reviews', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pois')
    # ### end Alembic commands ###
